AppBay_BackEnd/Models/Card.cs
namespace AppBay_BackEnd.Models
{
    public class Card
    {
        public int Id { get; set; }
        public string IconPath { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
    }
}

AppBay_BackEnd/Models/Modern.cs
namespace AppBay_BackEnd.Models
{
    public class Modern
    {
        public int Id { get; set; }
        public string IconPath { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
    }
}

AppBay_BackEnd/Models/Slider.cs
namespace AppBay_BackEnd.Models
{
    public class Slider
    {
        public int Id { get; set; }
        public string ImageUrlBackGround { get; set; }
        public string ImageUrl { get; set; }
    }
}

AppBay_BackEnd/ViewModels/HomeVM.cs
using AppBay_BackEnd.Models;
using System.Collections.Generic;

namespace AppBay_BackEnd.ViewModels
{
    public class HomeVM
    {
       public Slider sliders { get; set; }
       public IEnumerable<Card> cards { get; set; } 
       public IEnumerable<Modern> moderns { get; set; }

    }
}

AppBay_BackEnd/Areas/Admin/Controllers/CardController.cs
using AppBay_BackEnd.DAL;
using AppBay_BackEnd.Models;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AppBay_BackEnd.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CardController : Controller
    {
        private AppDbContext _context;
        public CardController(AppDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            List<Card> card = _context.Cards.ToList();
            return View(card);
        }
        public async Task<IActionResult> Detail(int? id)
        {
            if (id == null) return NotFound();
            Card card = await _context.Cards.FindAsync(id);
            if (card == null) return NotFound();
            return View(card);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null) return NotFound();
            Card card = await _context.Cards.FindAsync(id);
            if (card == null) return NotFound();
            _context.Cards.Remove(card);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(Card card)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            Card newcard=new Card();
            newcard.IconPath = card.IconPath;
            newcard.Title = card.Title;
            newcard.Description = card.Description;
            await _context.Cards.AddAsync(newcard);
            await _context.SaveChangesAsync();
            return View();
        }
    }
}

AppBay_BackEnd/Areas/Admin/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Mvc;

namespace AppBay_BackEnd.Areas.Admin
{
    [Area("Admin")]
    public class DashboardController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

AppBay_BackEnd/Areas/Admin/Views/Card/Create.cshtml
@model Card
@{
    ViewData["Title"] = "Create";
}

<div class="container">
    <div class="row">
         <form class="forms-sample" method="post">
                    <div class="form-group">
                      <label asp-for="IconPath" >Icon</label>
                      <input asp-for="IconPath" placeholder="Icon">
                      <span class="text-danger" asp-validation-for="IconPath"></span>
                    </div>
                    <div class="form-group">
                      <label asp-for="Title">Title</label>
                      <input asp-for="Title" placeholder="Title">
                      <span class="text-danger" asp-validation-for="Title"></span>
                    </div>
                    <div class="form-group">
                      <label asp-for="Description">Description</label>
                      <input asp-for="Description" placeholder="Description">
                      <span class="text-danger" asp-validation-for="Description"></span>
                    </div>
                    <button type="submit" class="btn btn-primary mr-2">Submit</button>
                    <button class="btn btn-light" asp-controller="Card" asp-action="Index">Back</button>
          </form>
    </div>
</div>

AppBay_BackEnd/Areas/Admin/Views/Card/Detail.cshtml
@model Card
@{
    ViewData["Title"] = "Detail";
}

<h2>Id:@Model.Id</h2>
<h4>Description:@Model.Description</h4>
<a class="btn btn-dark" asp-controller="Card" asp-action="Index" >Back</a>

AppBay_BackEnd/Areas/Admin/Views/Card/Index.cshtml
@model IEnumerable<Card>
@{
    ViewData["Title"] = "Index";
    int count = 0;
}

         <div class="row">
            <div class="col-lg-12 grid-margin stretch-card">
              <div class="card">
                <div class="card-body">
                  <h4 class="card-title">Card Table</h4>
                  <a class="btn btn-success" asp-action="Create" asp-controller="Card">Create</a>
                  <div class="table-responsive">
                    <table class="table">
                        <thead>
                        <tr>
                          <th>Count</th>
                          <th>Icon</th>
                          <th>Title</th>
                          <th>Setting</th>
                        </tr>
                      </thead>
                      <tbody>
                           @foreach (var item in Model)
                        {
                            count++;
                        <tr>
                          <td>@count</td>
                          <td>@item.IconPath</td>
                          <td>@item.Title</td>
                          <td>
                              <a class="btn btn-primary" asp-action="Update" asp-controller="Card"> <i class="mdi mdi-tooltip-edit"></i></a>
                         <a class="btn btn-danger" asp-action="Delete" asp-controller="Card" asp-route-id="@item.Id"><i class="mdi mdi-delete"></i> </a>
                         <a class="btn btn-info"  asp-action="Detail" asp-controller="Card" asp-route-id="@item.Id">   <i class="mdi mdi-information"></i> </a>
                          </td>
                        </tr>
                        
                        }
                      </tbody>
                       
                    </table>
                  </div>
                </div>
              </div>
            </div>
         </div>

AppBay_BackEnd/Areas/Admin/Views/Dashboard/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1>Dashboard</h1>

AppBay_BackEnd/Areas/Admin/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Majestic Admin</title>
  <!-- plugins:css -->
  <link rel="stylesheet" href="~/Admin/vendors/mdi/css/materialdesignicons.min.css">
  <link rel="stylesheet" href="~/Admin/vendors/base/vendor.bundle.base.css">
  <!-- endinject -->
  <!-- plugin css for this page -->
  <link rel="stylesheet" href="~/Admin/vendors/datatables.net-bs4/dataTables.bootstrap4.css">
  <!-- End plugin css for this page -->
  <!-- inject:css -->
  <link rel="stylesheet" href="~/Admin/css/style.css">
  <!-- endinject -->
  <link rel="shortcut icon" href="~/Admin/images/favicon.png" />
</head>
<body>
  <div class="container-scroller">
    <!-- partial:partials/_navbar.html -->
    <nav class="navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
      <div class="navbar-brand-wrapper d-flex justify-content-center">
        <div class="navbar-brand-inner-wrapper d-flex justify-content-between align-items-center w-100">  
          <a class="navbar-brand brand-logo" href="index.html"><img src="~/Admin/images/logo.svg" alt="logo"/></a>
          <a class="navbar-brand brand-logo-mini" href="index.html"><img src="~/Admin/images/logo-mini.svg" alt="logo"/></a>
          <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
            <span class="mdi mdi-sort-variant"></span>
          </button>
        </div>  
      </div>
      <div class="navbar-menu-wrapper d-flex align-items-center justify-content-end">
        <ul class="navbar-nav mr-lg-4 w-100">
          <li class="nav-item nav-search d-none d-lg-block w-100">
            <div class="input-group">
              <div class="input-group-prepend">
                <span class="input-group-text" id="search">
                  <i class="mdi mdi-magnify"></i>
                </span>
              </div>
              <input type="text" class="form-control" placeholder="Search now" aria-label="search" aria-describedby="search">
            </div>
          </li>
        </ul>
        <ul class="navbar-nav navbar-nav-right">
          <li class="nav-item dropdown mr-1">
            <a class="nav-link count-indicator dropdown-toggle d-flex justify-content-center align-items-center" id="messageDropdown" href="#" data-toggle="dropdown">
              <i class="mdi mdi-message-text mx-0"></i>
              <span class="count"></span>
            </a>
            <div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="messageDropdown">
              <p class="mb-0 font-weight-normal float-left dropdown-header">Messages</p>
              <a class="dropdown-item">
                <div class="item-thumbnail">
                    <img src="~/Admin/images/faces/face4.jpg" alt="image" class="profile-pic">
                </div>
                <div class="item-content flex-grow">
                  <h6 class="ellipsis font-weight-normal">David Grey
                  </h6>
                  <p class="font-weight-light small-text text-muted mb-0">
                    The meeting is cancelled
                  </p>
                </div>
              </a>
              <a class="dropdown-item">
                <div class="item-thumbnail">
                    <img src="~/Admin/images/faces/face2.jpg" alt="image" class="profile-pic">
                </div>
                <div class="item-content flex-grow">
                  <h6 class="ellipsis font-weight-normal">Tim Cook
                  </h6>
                  <p class="font-weight-light small-text text-muted mb-0">
                    New product launch
                  </p>
                </div>
              </a>
              <a class="dropdown-item">
                <div class="item-thumbnail">
                    <img src="~/Admin/images/faces/face3.jpg" alt="image" class="profile-pic">
                </div>
                <div class="item-content flex-grow">
                  <h6 class="ellipsis font-weight-normal"> Johnson
                  </h6>
                  <p class="font-weight-light small-text text-muted mb-0">
                    Upcoming board meeting
                  </p>
                </div>
              </a>
            </div>
          </li>
          <li class="nav-item dropdown mr-4">
            <a class="nav-link count-indicator dropdown-toggle d-flex align-items-center justify-content-center notification-dropdown" id="notificationDropdown" href="#" data-toggle="dropdown">
              <i class="mdi mdi-bell mx-0"></i>
              <span class="count"></span>
            </a>
            <div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="notificationDropdown">
              <p class="mb-0 font-weight-normal float-left dropdown-header">Notifications</p>
              <a class="dropdown-item">
                <div class="item-thumbnail">
                  <div class="item-icon bg-success">
                    <i class="mdi mdi-information mx-0"></i>
                  </div>
                </div>
                <div class="item-content">
                  <h6 class="font-weight-normal">Application Error</h6>
                  <p class="font-weight-light small-text mb-0 text-muted">
                    Just now
                  </p>
                </div>
              </a>
              <a class="dropdown-item">
                <div class="item-thumbnail">
                  <div class="item-icon bg-warning">
                    <i class="mdi mdi-settings mx-0"></i>
                  </div>
                </div>
                <div class="item-content">
                  <h6 class="font-weight-normal">Settings</h6>
                  <p class="font-weight-light small-text mb-0 text-muted">
                    Private message
                  </p>
                </div>
              </a>
              <a class="dropdown-item">
                <div class="item-thumbnail">
                  <div class="item-icon bg-info">
                    <i class="mdi mdi-account-box mx-0"></i>
                  </div>
                </div>
                <div class="item-content">
                  <h6 class="font-weight-normal">New user registration</h6>
                  <p class="font-weight-light small-text mb-0 text-muted">
                    2 days ago
                  </p>
                </div>
              </a>
            </div>
          </li>
          <li class="nav-item nav-profile dropdown">
            <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" id="profileDropdown">
              <img src="~/Admin/images/faces/face5.jpg" alt="profile"/>
              <span class="nav-profile-name">Louis Barnett</span>
            </a>
            <div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="profileDropdown">
              <a class="dropdown-item">
                <i class="mdi mdi-settings text-primary"></i>
                Settings
              </a>
              <a class="dropdown-item">
                <i class="mdi mdi-logout text-primary"></i>
                Logout
              </a>
            </div>
          </li>
        </ul>
        <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
          <span class="mdi mdi-menu"></span>
        </button>
      </div>
    </nav>
    <!-- partial -->
    <div class="container-fluid page-body-wrapper">
      <!-- partial:partials/_sidebar.html -->
      <nav class="sidebar sidebar-offcanvas" id="sidebar">
        <ul class="nav">
          <li class="nav-item">
            <a class="nav-link"  asp-area="Admin" asp-controller="Dashboard" asp-action="index">
              <i class="mdi mdi-home menu-icon"></i>
              <span class="menu-title" >Dashboard</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" asp-area="Admin" asp-controller="Card" asp-action="Index">
              <i class="mdi mdi-view-headline menu-icon"></i>
              <span class="menu-title">Card</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="pages/charts/chartjs.html">
              <i class="mdi mdi-chart-pie menu-icon"></i>
              <span class="menu-title">Charts</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="pages/tables/basic-table.html">
              <i class="mdi mdi-grid-large menu-icon"></i>
              <span class="menu-title">Tables</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="pages/icons/mdi.html">
              <i class="mdi mdi-emoticon menu-icon"></i>
              <span class="menu-title">Icons</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="documentation/documentation.html">
              <i class="mdi mdi-file-document-box-outline menu-icon"></i>
              <span class="menu-title">Documentation</span>
            </a>
          </li>
        </ul>
      </nav>
      <!-- partial -->
      <div class="main-panel">
        <div class="content-wrapper">
        @RenderBody()
        </div>
<footer class="footer">
          <div class="d-sm-flex justify-content-center justify-content-sm-between">
            <span class="text-muted text-center text-sm-left d-block d-sm-inline-block">Copyright © 2018 <a href="https://www.bootstrapdash.com/" target="_blank">Bootstrapdash</a>. All rights reserved.</span>
            <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">Hand-crafted & made with <i class="mdi mdi-heart text-danger"></i></span>
          </div>
        </footer>
        <!-- partial -->
      </div>
      <!-- main-panel ends -->
    </div>
    <!-- page-body-wrapper ends -->
  </div>
  <!-- container-scroller -->

  <!-- plugins:js -->
  <script src="~/Admin/vendors/base/vendor.bundle.base.js"></script>
  <!-- endinject -->
  <!-- Plugin js for this page-->
  <script src="~/Admin/vendors/chart.js/Chart.min.js"></script>
  <script src="~/Admin/vendors/datatables.net/jquery.dataTables.js"></script>
  <script src="~/Admin/vendors/datatables.net-bs4/dataTables.bootstrap4.js"></script>
  <!-- End plugin js for this page-->
  <!-- inject:js -->
  <script src="~/Admin/js/off-canvas.js"></script>
  <script src="~/Admin/js/hoverable-collapse.js"></script>
  <script src="~/Admin/js/template.js"></script>
  <!-- endinject -->
  <!-- Custom js for this page-->
  <script src="~/Admin/js/dashboard.js"></script>
  <script src="~/Admin/js/data-table.js"></script>
  <script src="~/Admin/js/jquery.dataTables.js"></script>
  <script src="~/Admin/js/dataTables.bootstrap4.js"></script>
  <!-- End custom js for this page-->
</body>

</html>

AppBay_BackEnd/Views/Home/Index.cshtml
@model HomeVM
@{
       ViewData["Title"] = "Index";
}
<main>
          <!-- Slider Start -->
          <section class="slider">
            <div id="carouselExampleSlidesOnly" class="carousel slide" data-bs-ride="carousel">
                <div class="carousel-inner">
                  <div class="carousel-item active">
                    <img src="~/img/@Model.sliders.ImageUrlBackGround" class="d-block w-100 slider-img" alt="...">
                  </div>
                  <div class="col-6 slider-mobile">
                    <img src="~/img/@Model.sliders.ImageUrl" alt="">
                  </div>
                  <!-- <div class="col-6 slider-text">
                    <h1>Responsive Page Landing Page</h1>
                    <h4>Bootstrap Based Responsive Landing Page Template.</h4>
                    <div class="app-download">
                      <a class="navbar-brand" href="#"><i class="fa-solid fa-mobile-screen slider-icon"></i>
                        <span class="available">Available on the</span>
                        <span class="appstore">App Store</span>
                    </a>
                    </div> 
                  </div>-->
                </div>
              </div>
          </section>
        <!-- Slider End -->
        <!-- Card Start -->
        <section class="card">
         <div class="container">
          <div class="row">
            <div class="row row-cols-1 row-cols-md-3 g-4">
                @foreach (var item in Model.cards)
                    {
              <div class="col">
                <div class="card h-100 text-center card-area">
                  <i class="@item.IconPath"></i>
                  <div class="card-body">
                    <h5 class="card-title">@item.Title</h5>
                    <p class="card-text">@item.Description</p>
                  </div>
                </div>
              </div>
                    }
            </div>
          </div>
         </div>

        </section>
        <!-- Card End -->
        <!--Modern Start  -->
        <section class="modern">
          <div class="container">
            <div class="row">
              <div class="section-title text-center mt-5">
                <h3 class="modern-title">Modern & clean landing page theme</h3>
                <p class="modern-subtitle">Lorem ipsum dolizzle sit tellivizzle, boom shackalack adipiscing elit. Nullam mofo velizzle, sure cool.</p>
              </div>
            </div>
            <div class="modern-context d-flex">
              <div class="col-6 modern-img">
                <img src="~/img/tablet.png">
              </div>
              <div class="col-6 modern-context">
                        @foreach (var item in Model.moderns)
                            {
                                 <div class="card mb-3 modern-card" style="max-width: 540px;">
                    <div class="row g-0">
                                 <div class="col-2">
                        <i class="@item.IconPath"></i>
                      </div>
                      <div class="col-md-8">
                        <div class="card-body">
                          <h5 class="card-title">@item.Title</h5>
                          <p class="card-text">@item.Description</p>
                        </div>
                      </div>
                      
                    </div>
                     
                  </div>
                            }
                            
            </div>
        </div>
    </div>
        </section>
        <!--Modern End  -->
        <!-- TextSlider Start -->
        <section class="TextSlider">
          <div class="container">
            <div class="row">
              <p class="textslider-text text-center" style="color:blue;">What people say</p>
              <div id="slider">
                <ul>
                  <li>
                  <div class="slider-container">
                    <p>“Went with my wife, absolutely brilliant restaurant, the food tasted beautiful, so much depth and very well presented. As good if not better than any in the city centre. Will definitely be returning.” <br> Nathaniel Harwood – Google</p>
                  </div>
                  </li>
                    <li>
                    <div class="slider-container">
                    <p>“Great friendly service, the staff don't make you feel rushed, but are also very attentive, and on hand all the time if needed, best Thai food I have had in years, flavours are out of this world, and extremely good prices for the quality you get is top notch!!!!!! Love it” <br>David Armstrong - Porter – Google</p>
                  </div>
                  </li>
                    <li>
                    <div class="slider-container">
                    <p>“Possibly one of the best in Manchester. A menu designed and prepared by a very skilled chef, ably assisted by his wife who provides a friendly welcome. Always consistent and of high quality.” <br>Paul Fletcher – Google</p>
                  </div>
                  </li>
                    <li>
                    <div class="slider-container">
                    <p>“Food was amazing and service could not have been better...we went for a quick lunch as our office is opposite the restaurant...very quick service...I am highly recommending this restaurant to all my family and friends...” <br>Nic Gent – Facebook Page</p>
                  </div>
                  </li>
                   <li>
                    <div class="slider-container">
                    <p>“Went for the first time last night for my Husbands Birthday, friendly staff, very tasty food, would highly recommend, we will be back.” <br>Joanne Simms – Facebook Page</p>
                  </div>
                  </li>
                   <li>
                    <div class="slider-container">
                    <p>“A lovely, well decorated restaurant, where great food is served by very friendly staff for a bargain price. The food is authentic and delicious. We'll definitely be returning.”<br>Joe H – Trip Advisor</p>
                  </div>
                  </li>
                </ul>
                </div>
                
            </div>
          </div>
        </section>
        <!-- TextSlider End -->
    </main>

AppBay_BackEnd/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="~/css/style.css">
    <title>AppBay</title>
</head>
<body>
    <!-- Header Start -->
    <section id="header-stick">
   <div class="container">
    <div class="row">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
              <a class="navbar-brand" href="#"><i class="fa-solid fa-mobile-screen logo-icon"></i>
                <span class="app">App</span>
                <span class="bay">Bay</span>
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
              <div class="collapse navbar-collapse nav-main-list" id="navbarNavDropdown">
                <ul class="navbar-nav">
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">Features</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="#">The App</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="#">Pricing</a>
                  </li>
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                     Testimonials
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                      <li><a class="dropdown-item" href="#">Action</a></li>
                      <li><a class="dropdown-item" href="#">Another action</a></li>
                      <li><a class="dropdown-item" href="#">Something else here</a></li>
                    </ul>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="#">Contact Us</a>
                  </li>
                </ul>
              </div>
            </div>
          </nav>
    </div>
   </div>
  </section>
    <div>
        @RenderBody()
    </div>
    </body>
<footer>
  <div class="footer-basic">
  <p class="copyright">Company Name © 2022 AppBay All Rights Reserved | Built by ILKINIBRA</p>
  <div class="social"><a href="#"><i class="icon ion-social-instagram"></i></a><a href="#"><i class="icon ion-social-snapchat"></i></a><a href="#"><i class="icon ion-social-twitter"></i></a><a href="#"><i class="icon ion-social-facebook"></i></a></div>
  </div>
</footer>
<script src="~/js/script.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</html>